trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  solutionName: 'xam2.sln'
  androidProject: 'xam2.Android/xam2.Android.csproj'

stages:
- stage: BuildApps
  displayName: "Build The Apps"
  jobs:

  - job: BuildAndroid
    displayName: "Build Android App"

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solutionName)'

    - task: XamarinAndroid@1
      inputs:
        projectFile: '$(androidProject)'
        outputDirectory: '$(outputDirectory)'
        configuration: '$(buildConfiguration)'

    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/*.apk'
        apksignerKeystoreFile: 'xam2.keystore'
        apksignerKeystorePassword: '$(keystorePassword)'
        apksignerKeystoreAlias: '$(keystoreName)'
        apksignerKeyPassword: '$(keystorePassword)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'xam2.Android/obj/Release/android/bin/ch.bzumbuehl.xam2.apk'
        artifactName: AndroidApk



  - job: BuildiOS
    displayName: "Build iOS App"

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solutionName)'

    - task: InstallAppleCertificate@2
      inputs:
        certSecureFile: 'Zertifikate.p12'
        certPwd: '$(keystorePassword)'

    - task: InstallAppleProvisioningProfile@1
      inputs:
        provisioningProfileLocation: 'secureFiles'
        provProfileSecureFile: 'Ad_Hoc_2021_07_16.mobileprovision'


    - task: XamariniOS@2
      inputs:
        solutionFile: '$(solutionName)'
        configuration: '$(buildConfiguration)'
        packageApp: true
        buildForSimulator: false
        runNugetRestore: false
        signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
        signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'xam2.iOS/bin/iPhone/Release/xam2.iOS.ipa'
        artifactName: iOSIpa


- stage: BetaVersions
  dependsOn: BuildApps
  displayName: "Beta Release"
  jobs:
  - job: AndroidBeta
    displayName: "Release Android Beta"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: AndroidApk
    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'App Center'
        appSlug: 'Xam2/Xam2-1'
        appFile: '$(Pipeline.Workspace)/ch.bzumbuehl.xam2.apk'
        releaseNotesOption: 'file'
        releaseNotesFile: 'releasenotes.txt'
        destinationType: 'groups'
        distributionGroupId: 'f1e589a5-1fea-4935-b59a-2377d6070d60'

  - job: iOSBeta
    displayName: "Release iOS Beta"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: iOSIpa
    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'App Center'
        appSlug: 'xam2/xam2'
        appFile: '$(Pipeline.Workspace)/xam2.iOS.ipa'
        releaseNotesOption: 'file'
        releaseNotesFile: 'releasenotes.txt'
        destinationType: 'groups'
        distributionGroupId: '14022a20-e918-4157-b0da-6a08cea279ee'  